name: CI

on: [push]
env:
  XDEBUG_MODE: coverage
jobs:
  build-71:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v6
        with:
          version: 1
          php_version: "7.1"
      - name: PHP Unit
        uses: php-actions/phpunit@v3
        with:
          version: 7.5
          php_version: "7.1"
  build-74:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
      - name: PHP Unit
        uses: php-actions/phpunit@v3
        with:
          version: 7.5
          php_version: "7.4"
          php_extensions: xdebug
          args: --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v3
